### Site Settings ###
title               : Shubham Suryavanshi
description         : >-
                      Android Developer // Google India Scholar
baseurl             : ""
repository          : Shubham7819/Shubham7819.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Shubham Suryavanshi
  image             : https://media-exp3.licdn.com/dms/image/C5103AQFzbDPvRDh3zg/profile-displayphoto-shrink_200_200/0/1518933864572?e=1631750400&v=beta&t=HKTmdCXrZCYYFLxeq2ch3jn-qYRnmNyCmd-fH1k_NOM
# behance           : your_username
# dribbble          : your_username
  email             : shubham7819@gmail.com
# facebook          : your_username
  github            : Shubham7819
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : shubham-suryawanshi
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
  stackoverflow     : 10553536
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
# disqus:
#   shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
